# Global variables

# Event types
EVENT_STATE_CHANGE_ON = "EVENT_STATE_CHANGE_ON"
EVENT_STATE_CHANGE_OFF = "EVENT_STATE_CHANGE_OFF"

# Supported device types
DEVICE_TYPE_LIGHT = 'DEVICE_TYPE_LIGHT'
DEVICE_TYPE_BINARY_SENSOR = 'DEVICE_TYPE_BINARY_SENSOR'